CREATE TYPE user_role AS ENUM
    (
        'guest',
        'member',
        'referral',
        'company',
        'moderator',
        'admin'
        );

CREATE TYPE test_session_type AS ENUM
    (
        'selection-system',
        'marathon',
        'mistake',
        'module',
        'exam'
        );

CREATE TYPE status AS ENUM
    (
        'created',
        'active',
        'inactive'
        );

CREATE TYPE question_type AS ENUM
    (
        'single_choice',
        'multiple_choice',
        'plaintext'
        );

CREATE TABLE IF NOT EXISTS files
(
    id          SERIAL PRIMARY KEY,
    uuid        uuid         NOT NULL,
    content     VARCHAR(255) NOT NULL,
    size        INTEGER      NOT NULL,
    mime_type   VARCHAR(255) NOT NULL,
    origin_name VARCHAR(255) NOT NULL,
    created_by  INTEGER      NOT NULL,
    deleted_at  TIMESTAMP    NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX files_uuid_unique_index ON files (uuid);
CREATE INDEX files_deleted_at_not_null_index ON files (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS users
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    uuid               uuid                          NOT NULL,
    email              VARCHAR(255)                  NULL,
    first_name         VARCHAR(255)                  NULL,
    last_name          VARCHAR(255)                  NULL,
    role               user_role                     NOT NULL,
    password           VARCHAR(255)                  NULL,
    avatar_id          INTEGER references files (id) NULL,
    description        TEXT                          NULL,
    company_name       VARCHAR(255)                  NULL,
    contact            VARCHAR(255)                  NULL,
    account            INTEGER                       NOT NULL DEFAULT 0,
    can_view_referrals BOOLEAN                       NOT NULL DEFAULT FALSE,
    deleted_at         TIMESTAMP                     NULL,
    created_at         TIMESTAMP                     NOT NULL,
    updated_at         TIMESTAMP                     NOT NULL
);

ALTER TABLE files
    ADD CONSTRAINT files_created_by_foreign FOREIGN KEY (created_by) REFERENCES users (id);

CREATE TABLE IF NOT EXISTS courses
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    uuid              uuid                          NOT NULL,
    name              VARCHAR(255)                  NOT NULL,
    description       text                          NOT NULL,
    color             VARCHAR(50)                   NOT NULL,
    icon              VARCHAR(50)                   NOT NULL,
    status            status                        NOT NULL,
    moderation_reason TEXT                          NULL,
    created_by        INTEGER references users (id) NOT NULL,
    moderated_by      INTEGER references users (id) NULL,
    deleted_at        TIMESTAMP                     NULL,
    created_at        TIMESTAMP                     NOT NULL,
    updated_at        TIMESTAMP                     NOT NULL
);

CREATE TABLE IF NOT EXISTS modules
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    uuid              uuid                            NOT NULL,
    name              varchar(255)                    NOT NULL,
    status            status                          NOT NULL,
    moderation_reason TEXT                            NULL,
    course_id         INTEGER references courses (id) NOT NULL,
    created_by        INTEGER references users (id)   NOT NULL,
    moderated_by      INTEGER references users (id)   NULL,
    deleted_at        TIMESTAMP                       NULL,
    created_at        TIMESTAMP                       NOT NULL,
    updated_at        TIMESTAMP                       NOT NULL
);

CREATE TABLE IF NOT EXISTS questions
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    uuid              uuid                              NOT NULL,
    title             text                              NOT NULL,
    content           text                              NULL,
    explanation       text                              NULL,
    moderation_reason TEXT                              NULL,
    type              question_type                     NOT NULL,
    status            status                            NOT NULL,
    course_id         INTEGER references courses (id)   NOT NULL,
    module_id         INTEGER references modules (id)   NULL,
    created_by        INTEGER references users (id)     NOT NULL,
    moderated_by      INTEGER references users (id)     NULL,
    prev_question_id  INTEGER references questions (id) NULL,
    next_question_id  INTEGER references questions (id) NULL,
    options           jsonb                             NOT NULL,
    deleted_at        TIMESTAMP                         NULL,
    created_at        TIMESTAMP                         NOT NULL,
    updated_at        TIMESTAMP                         NOT NULL
);

CREATE UNIQUE INDEX questions_uuid_unique_index ON questions (uuid);
CREATE INDEX questions_deleted_at_not_null_index ON questions (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX questions_course_id_index ON questions (course_id);

CREATE TABLE IF NOT EXISTS test_sessions
(
    id               SERIAL PRIMARY KEY,
    uuid             uuid                              NOT NULL,
    name             VARCHAR(255)                      NOT NULL,
    type             test_session_type                 NOT NULL,
    user_id          INTEGER references users (id)     NOT NULL,
    course_id        INTEGER references courses (id)   NULL,
    question_ids     integer[]                         NOT NULL,
    last_question_id INTEGER references questions (id) NULL,
    deleted_at       TIMESTAMP                         NULL,
    created_at       TIMESTAMP                         NOT NULL,
    updated_at       TIMESTAMP                         NOT NULL
);

CREATE UNIQUE INDEX test_sessions_uuid_unique_index ON test_sessions (uuid);
CREATE INDEX test_sessions_deleted_at_not_null_index ON test_sessions (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_answers
(
    id              SERIAL PRIMARY KEY,
    test_session_id INTEGER references test_sessions (id) NOT NULL,
    question_id     INTEGER references questions (id)     NOT NULL,
    answer_data     JSONB                                 NOT NULL,
    is_correct      BOOLEAN                               NOT NULL,
    answered_at     TIMESTAMP                             NOT NULL
);

CREATE INDEX user_answers_test_session_id_index ON user_answers (test_session_id);

CREATE TABLE IF NOT EXISTS tags
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO tags (id, name)
VALUES (1, 'Разработка ПО'),
       (2, 'Frontend'),
       (3, 'Backend'),
       (4, 'Проектирование баз данных'),
       (5, 'Разработка под iOS'),
       (6, 'Разработка под Android'),
       (7, 'System Design'),
       (8, 'Аналитика данных и ИИ'),
       (9, 'Разработка десктопных приложений'),
       (10, 'Создание игр'),
       (11, 'Системное администрирование и DevOps'),
       (12, 'Управление серверами и сетями'),
       (13, 'Контейнеризация и оркестрация (Docker, Kubernetes)'),
       (14, 'Непрерывная интеграция и развертывание (CI/CD)'),
       (15, 'Информационная безопасность'),
       (16, 'Кибербезопасность'),
       (17, 'Защита данных и нормативное соответствие'),
       (18, 'Управление угрозами и уязвимостями'),
       (19, 'Анализ данных и бизнес-аналитика'),
       (20, 'Машинное обучение и глубокое обучение'),
       (21, 'Обработка естественного языка'),
       (22, 'Сетевые технологии'),
       (23, 'Сетевое администрирование'),
       (24, 'Протоколы и сетевые архитектуры'),
       (25, 'Базы данных и хранение данных'),
       (26, 'Администрирование БД'),
       (27, 'Управление большими данными'),
       (28, 'Облачные технологии'),
       (29, 'Облачные платформы (AWS, Azure, Google Cloud)'),
       (30, 'Архитектура облачных решений'),
       (31, 'Управление облачными услугами'),
       (32, 'Проектный менеджмент в IT'),
       (33, 'Управление продуктом'),
       (34, 'Управление командами разработки'),
       (35, 'Разработка встроенных систем'),
       (36, 'Программирование микроконтроллеров'),
       (37, 'Создание IoT-устройств'),
       (38, 'Разработка VR и AR приложений'),
       (39, 'Технологии блокчейна и криптовалюта');

CREATE TABLE IF NOT EXISTS question_tag
(
    question_id INTEGER references questions (id) NOT NULL,
    tag_id      INTEGER references tags (id)      NOT NULL,
    PRIMARY KEY (question_id, tag_id)
);

CREATE TABLE IF NOT EXISTS user_experience
(
    id         SERIAL PRIMARY KEY,
    user_id    INTEGER REFERENCES users (id) NOT NULL,
    one        SMALLINT                      NOT NULL,
    two        SMALLINT                      NOT NULL,
    three      SMALLINT                      NOT NULL,
    four       VARCHAR(255)                  NOT NULL,
    five       SMALLINT                      NOT NULL,
    six        SMALLINT                      NOT NULL,
    seven      VARCHAR(255)                  NOT NULL,
    eight      VARCHAR(255)                  NOT NULL,
    nine       SMALLINT                      NOT NULL,
    ten        VARCHAR(255)                  NOT NULL,
    eleven     SMALLINT                      NOT NULL,
    twelve     VARCHAR(255)                  NOT NULL,
    thirteen   VARCHAR(255)                  NOT NULL,
    deleted_at TIMESTAMP                     NULL,
    created_at TIMESTAMP                     NOT NULL,
    updated_at TIMESTAMP                     NOT NULL
);
